# Logging and Error Handling
logging:
  log_path: "src/data_pipeline/logs/preprocessed/preprocessing.log"
  log_level: "INFO"

# DVC-tracked output path (processed data)
output_path: "data/processed/preprocessed.csv"

# Target variable
target_column: "churn"

# Columns to drop during preprocessing
drop_columns:
  - "Unnamed: 0"
  - "X"
  - "customer"
  - "traintest"
  - "churndep"

numerical_features:
  - "revenue"
  - "mou"
  - "recchrge"
  - "directas"
  - "overage"
  - "roam"
  - "changem"
  - "changer"
  - "dropvce"
  - "blckvce"
  - "unansvce"
  - "custcare"
  - "threeway"
  - "mourec"
  - "outcalls"
  - "incalls"
  - "peakvce"
  - "opeakvce"
  - "dropblk"
  - "callfwdv"
  - "callwait"
  - "months"
  - "uniqsubs"
  - "actvsubs"
  - "phones"
  - "models"
  - "eqpdays"
  - "age1"
  - "age2"
  - "refer"
  - "income"
  - "setprc"

categorical_features:
  - "children"
  - "credita"
  - "creditaa"
  - "prizmrur"
  - "prizmub"
  - "prizmtwn"
  - "refurb"
  - "webcap"
  - "truck"
  - "rv"
  - "occprof"
  - "occcler"
  - "occcrft"
  - "occstud"
  - "occhmkr"
  - "occret"
  - "occself"
  - "ownrent"
  - "marryun"
  - "marryyes"
  - "mailord"
  - "mailres"
  - "mailflag"
  - "travel"
  - "pcown"
  - "creditcd"
  - "newcelly"
  - "newcelln"
  - "incmiss"
  - "mcycle"
  - "setprcm"
  - "retcall"
  - "retcalls"
  - "retaccpt"

combined_features:
  - "engagement_index"     # (outcalls + incalls) / (months + 1)
  - "model_change_rate"    # models / (months + 1)
  - "overage_ratio"        # overage / (revenue + 1)

schema:
  revenue:          { dtype: "float", allow_null: false }
  mou:              { dtype: "float",  allow_null: false }
  recchrge:         { dtype: "float",  allow_null: false }
  directas:         { dtype: "float",  allow_null: true }
  roam:             { dtype: "float", allow_null: true }
  changem:          { dtype: "float",  allow_null: true }
  changer:          { dtype: "float",  allow_null: true }
  dropvce:          { dtype: "float",  allow_null: true }
  blckvce:          { dtype: "float",  allow_null: true }
  unansvce:         { dtype: "float",  allow_null: true }
  custcare:         { dtype: "float",  allow_null: true }
  threeway:         { dtype: "float",  allow_null: true }
  mourec:           { dtype: "float",  allow_null: true }
  peakvce:          { dtype: "float",  allow_null: true }
  opeakvce:         { dtype: "float",  allow_null: true }
  dropblk:          { dtype: "float",  allow_null: true }
  callfwdv:         { dtype: "float",  allow_null: true }
  callwait:         { dtype: "float",  allow_null: true }
  months:           { dtype: "float",  allow_null: false }
  uniqsubs:         { dtype: "float",  allow_null: false }
  actvsubs:         { dtype: "float",  allow_null: false }
  phones:           { dtype: "float",  allow_null: false }
  eqpdays:          { dtype: "float", allow_null: true }
  age1:             { dtype: "float",  allow_null: true }
  age2:             { dtype: "float",  allow_null: true }
  refer:            { dtype: "float",  allow_null: true }
  income:           { dtype: "float",  allow_null: true }
  setprc:           { dtype: "float",  allow_null: true }
  engagement_index: { dtype: "float", allow_null: true }
  model_change_rate: { dtype: "float", allow_null: true }
  overage_ratio:    { dtype: "float", allow_null: true }
  children:         { dtype: "int", allow_null: true }
  credita:          { dtype: "int", allow_null: true }
  creditaa:         { dtype: "int", allow_null: true }
  prizmrur:         { dtype: "int", allow_null: true }
  prizmub:          { dtype: "int", allow_null: true }
  prizmtwn:         { dtype: "int", allow_null: true }
  refurb:           { dtype: "int", allow_null: true }
  webcap:           { dtype: "int", allow_null: true }
  truck:            { dtype: "int", allow_null: true }
  rv:               { dtype: "int", allow_null: true }
  occprof:          { dtype: "int", allow_null: true }
  occcler:          { dtype: "int", allow_null: true }
  occcrft:          { dtype: "int", allow_null: true }
  occstud:          { dtype: "int", allow_null: true }
  occhmkr:          { dtype: "int", allow_null: true }
  occret:           { dtype: "int", allow_null: true }
  occself:          { dtype: "int", allow_null: true }
  ownrent:          { dtype: "int", allow_null: true }
  marryun:          { dtype: "int", allow_null: true }
  marryyes:         { dtype: "int", allow_null: true }
  mailord:          { dtype: "int", allow_null: true }
  mailres:          { dtype: "int", allow_null: true }
  mailflag:         { dtype: "int", allow_null: true }
  travel:           { dtype: "int", allow_null: true }
  pcown:            { dtype: "int", allow_null: true }
  creditcd:         { dtype: "int", allow_null: true }
  newcelly:         { dtype: "int", allow_null: true }
  newcelln:         { dtype: "int", allow_null: true }
  incmiss:          { dtype: "int", allow_null: true }
  mcycle:           { dtype: "int", allow_null: true }
  setprcm:          { dtype: "int", allow_null: true }
  retcall:          { dtype: "int", allow_null: true }
  retcalls:         { dtype: "int", allow_null: true }
  retaccpt:         { dtype: "int", allow_null: true }
  churn:            { dtype: "int", allowed_values: [0, 1], allow_null: false }
