# Logging and Error Handling
logging:
  log_path: "src/data/logs/preprocessing.log"
  log_level: "INFO"

output_path: "data/processed/cell2cell_processed.csv"
target_column: "churn"

drop_columns:
  - "Unnamed: 0"
  - "X"
  - "customer"
  - "traintest"
  - "churndep"
  # - "overage"
  # - "outcalls"
  # - "incalls"
  # - "models"


numerical_features:
- "revenue"
- "mou"
- "recchrge"
- "directas"
- "overage"
- "roam"
- "changem"
- "changer"
- "dropvce"
- "blckvce"
- "unansvce"
- "custcare"
- "threeway"
- "mourec"
- "outcalls"
- "incalls"
- "peakvce"
- "opeakvce"
- "dropblk"
- "callfwdv"
- "callwait"
- "months"
- "uniqsubs"
- "actvsubs"
- "phones"
- "models"
- "eqpdays"
- "age1"
- "age2"
- "refer"
- "income"
- "setprc"

categorical_features:  
  - "children"     
  - "credita"      
  - "creditaa"     
  - "prizmrur"     
  - "prizmub"      
  - "prizmtwn"     
  - "refurb"       
  - "webcap"       
  - "truck"        
  - "rv"           
  - "occprof"      
  - "occcler"      
  - "occcrft"     
  - "occstud"     
  - "occhmkr"      
  - "occret"       
  - "occself"      
  - "ownrent"      
  - "marryun"      
  - "marryyes"     
  - "mailord"     
  - "mailres"      
  - "mailflag"     
  - "travel"       
  - "pcown"       
  - "creditcd"     
  - "newcelly"     
  - "newcelln"     
  - "incmiss"      
  - "mcycle"       
  - "setprcm"      
  - "retcall" 
  - "retcalls"      
  - "retaccpt"

combined_features:
  - "engagement_index" # (outcalls+incalls/(months+1))
  - "model_change_rate" # (models/(months+1))
  - "overage_ratio" # (overage/(revenue + 1))