artifact_location: /Users/wycliffenzomo/Documents/pro/Project-repo/${MLFLOW_TRACKING_URI}/0
creation_time: 1761837905682
experiment_id: '0'
last_update_time: 1761837905682
lifecycle_stage: active
name: Default
